name: Deploy to AKS

on:
  push:
    branches:
      - Master  # Change this to the appropriate branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBE_CONFIG" > $HOME/.kube/config
        kubectl version  # Print kubectl version for verification

    - name: Deploy to AKS
      run: kubectl apply -f azure-vote.yaml
